#!/usr/bin/env bash

echo "File		| size (min + gzip) "
echo "----------------|-------------------"
	for f in *.less
	do
		name=${f%.less}
		echo "@import 'colors'; @import '$name';" |  lessc --clean-css="s1" - > $name.css
		gzip -k $name.css
		echo "$f	| $(wc -c $name.css.gz | cut -f1 -d ' ') "
		rm $name.css*
	done
